# Oh my zsh install path
export ZSH=~/.oh-my-zsh

# Theme
ZSH_THEME="oxide"

# History date format
HIST_STAMPS="mm/dd/yyyy"

# Plugins
plugins=(git)

# Launches Oh my zsh
source $ZSH/oh-my-zsh.sh

# Python virtualenvwrapper
source virtualenvwrapper_lazy.sh

# Sets Neovim has default editor
alias vim=nvim
export VISUAL=nvim

# Exports all installed python version (via Pythonz) to
# the user PATH
if [[ -s $HOME/.pythonz/etc/bashrc ]]
then
    source $HOME/.pythonz/etc/bashrc
    PATH=$PATH:$(pythonz list -p | awk 'BEGIN {ORS=":"} /^ / {print $2"/bin"}')
fi

# An colored alternative to ls
alias ls=exa

# fzf configs
[ -f /usr/share/fzf/key-bindings.zsh ] && source /usr/share/fzf/key-bindings.zsh

# Uses fd as default command showing also hidden files
FZF_DEFAULT_COMMAND="fd --hidden"

# ctrl+o opens Visual Studio Code on current folder or file
FZF_DEFAULT_OPTS="--bind='ctrl-o:execute-silent(code {})+abort'"

# If current selection is a text file shows its content,
# if it's a directory shows its content, the rest is ignored
FZF_CTRL_T_OPTS="--preview-window wrap --preview '
if [[ -f {} ]]; then
    file --mime {} | grep -q \"text\/.*;\" && bat --color \"always\" {} || (tput setaf 1; file --mime {})
elif [[ -d {} ]]; then
    exa -l --color always {}
else;
    tput setaf 1; echo YOU ARE NOT SUPPOSED TO SEE THIS!
fi'"

# Golang
export GOPATH=$HOME/go
PATH=$PATH:$(go env GOPATH)/bin

PATH=$PATH:$HOME/.local/bin

# Qbs
QBS_ROOT=$HOME/Qt/Tools/QtCreator/bin
PATH=$PATH:$QBS_ROOT

# Bat settings
alias cat='bat --style=numbers,changes,grid'
export BAT_THEME="Monokai Extended"

# Syntax highlighting
source /usr/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

# XAuthority
export XAUTHORITY=$HOME/.Xauthority

# Launches tmux if not already inside
[ $DISPLAY ] && [ -z $TMUX ] && tmux
