# Oh my zsh install path
export ZSH=~/.oh-my-zsh

# Theme
ZSH_THEME="robbyrussell"

# History date format
HIST_STAMPS="mm/dd/yyyy"

# Plugins
plugins=(git)

# Launches Oh my zsh
source $ZSH/oh-my-zsh.sh

# Adds global local/bin folder
PATH=/usr/local/bin:$PATH

# Python virtualenvwrapper
source virtualenvwrapper.sh

# Sets Neovim has default editor
alias vim=nvim
export VISUAL=nvim

# Exports all installed python version (via Pythonz) to
# the user PATH
if [[ -s $HOME/.pythonz/etc/bashrc ]]
then
    source $HOME/.pythonz/etc/bashrc
    PATH=$PATH:$(pythonz list -p | awk 'BEGIN {ORS=":"} /^ / {print $2"/bin"}')
fi

# Java
JAVA_HOME=/usr/local/java/jdk1.8.0_102
PATH=$PATH:$JAVA_HOME
export JAVA_HOME

# Android Studio
ANDROID_STUDIO=/usr/local/android-studio
PATH=$PATH:$ANDROID_STUDIO/bin

# Exercism
EXERCISM=$HOME/bin
PATH=$PATH:$EXERCISM

# QWT
QWT_ROOT=$HOME/local/qwt-6.1.3

# CMake
CMAKE_ROOT=/opt/cmake
PATH=$PATH:$CMAKE_ROOT/bin

# Go
GOROOT=/usr/local/go
GOPATH=$HOME/workspace/go
PATH=$PATH:$GOROOT/bin:$GOPATH

# Pico-8
PICO8_ROOT=$HOME/pico-8
PATH=$PATH:$PICO8_ROOT

# An colored alternative to ls
alias ls=exa

# fzf configs
[ -f /usr/share/fzf/key-bindings.zsh ] && source /usr/share/fzf/key-bindings.zsh

# Uses fd as default command showing also hidden files
FZF_DEFAULT_COMMAND="fd --hidden"

# ctrl+o opens Visual Studio Code on current folder or file
FZF_DEFAULT_OPTS="--bind='ctrl-o:execute-silent(code {})+abort'"

# If current selection is a text file shows its content,
# if it's a directory shows its content, the rest is ignored
FZF_CTRL_T_OPTS="--preview-window wrap --preview '
if [[ -f {} ]]; then
    file --mime {} | grep -q \"text\/.*;\" && bat --color \"always\" {} || (tput setaf 1; file --mime {})
elif [[ -d {} ]]; then
    exa -l --color always {}
else;
    tput setaf 1; echo YOU ARE NOT SUPPOSED TO SEE THIS!
fi'"

# Qbs
QBS_ROOT=$HOME/Qt/Tools/QtCreator/bin
PATH=$PATH:$QBS_ROOT

# Flutter
FLUTTER_ROOT=$HOME/flutter
PATH=$PATH:$FLUTTER_ROOT/bin

# Adds cookiecutter to PATH
PATH=$PATH:$HOME/.local/bin

# Adds binaries installed with yarn to PATH
PATH=$PATH:$HOME/.yarn/bin

# Bat settings
alias cat='bat --style=numbers,changes,grid'
export BAT_THEME="Monokai Extended"
